[versions]
agp = "8.5.1"
desugar_jdk_libs = "2.1.2"
kotlin = "2.0.0"
coreKtx = "1.15.0"
appcompat = "1.7.0"
lazycolumnscrollbar = "2.2.0"
material = "1.12.0"
androidxComposeBom = "2024.10.01"
media3Exoplayer = "1.4.1"
soraEditor = "0.23.4-c4e33c3-SNAPSHOT"
gson = "2.11.0"
dataStore = "1.1.1"
storage = "2.0.0"
cascade_compose = "2.3.0"
compose_swipebox = "1.4.0"
lifecycle_runtime_compose_android = "2.8.7"
activity_compose = "1.9.3"
lifecycle_runtime_ktx = "2.8.7"
coilCompose = "3.0.0-rc02"
zoomable = "1.6.2"
junit = "1.2.1"
espressoCore = "3.6.1"
uiautomator = "2.2.0"
benchmarkMacroJunit4 = "1.2.4"
baselineprofile = "1.2.4"
profileinstaller = "1.3.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coilCompose" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilCompose" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilCompose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-lifecycle-runtime-compose-android = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "lifecycle_runtime_compose_android" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity_compose" }
sora-editor = { group = "io.github.Rosemoe.sora-editor", name = "editor", version.ref = "soraEditor" }
sora-editor-language-java = { group = "io.github.Rosemoe.sora-editor", name = "language-java", version.ref = "soraEditor" }
sora-editor-language-textmate = { group = "io.github.Rosemoe.sora-editor", name = "language-textmate", version.ref = "soraEditor" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
storage = { group = "com.anggrayudi", name = "storage", version.ref = "storage" }
cascade-compose = { group = "me.saket.cascade", name = "cascade-compose", version.ref = "cascade_compose" }
compose-swipebox = { group = "io.github.kevinnzou", name = "compose-swipebox", version.ref = "compose_swipebox" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle_runtime_ktx" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose-android", version.ref = "coilCompose"}
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }


